"""Generate the IEC 60364-5-52 data modules from the one reference file.

    python testing/iec-60364-tables-review/build_iec_tables.py

Reads ``iec_60364_5_52_data.json`` (next to this script) and writes

  * backend/analysis/iec_60364_data.py
  * frontend/js/iec-60364-data.js

with identical values, so the backend DB-circuit check and the frontend
ampacity calculators can never drift. Never edit the generated files by hand
— change the JSON (after checking the value against IEC 60364-5-52) and
re-run this script.
"""
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
DATA = json.loads((HERE / "iec_60364_5_52_data.json").read_text())

# IEC 60364-5-52 Table B.52.1 reference installation methods. ``env`` picks
# the ambient-temperature table and the grouping family; ``tables`` names the
# capacity tables the method's values come from.
METHODS = [
    ("A1", "Insulated conductors in conduit in a thermally insulated wall", "air", "B.52.2–B.52.5"),
    ("A2", "Multi-core cable in conduit in a thermally insulated wall", "air", "B.52.2–B.52.5"),
    ("B1", "Insulated conductors in conduit on a wall (or in trunking)", "air", "B.52.2–B.52.5"),
    ("B2", "Multi-core cable in conduit on a wall (or in trunking)", "air", "B.52.2–B.52.5"),
    ("C", "Single- or multi-core cable direct on a wall (clipped)", "air", "B.52.2–B.52.5"),
    ("D1", "Multi- or single-core cable in ducts in the ground", "ground", "B.52.2–B.52.5"),
    ("D2", "Sheathed multi- or single-core cable direct in the ground", "ground", "B.52.2–B.52.5"),
    ("E", "Multi-core cable in free air (≥ 0.3 D from the wall)", "air", "B.52.10–B.52.13"),
    ("F", "Single-core cables touching in free air (3 loaded: trefoil)", "air", "B.52.10–B.52.13"),
    ("G", "Single-core cables spaced in free air (3 loaded, flat horizontal)", "air", "B.52.10–B.52.13"),
]

GROUP_LABELS = {
    "bunched": "Bunched in air / on a surface / enclosed (B.52.17 row 1)",
    "single_layer_wall_floor": "Single layer on wall, floor or unperforated tray (B.52.17 row 2)",
    "single_layer_under_ceiling": "Single layer directly under a wooden ceiling (B.52.17 row 3)",
    "single_layer_perforated_tray": "Single layer on perforated tray (B.52.17 row 4)",
    "single_layer_ladder_cleats": "Single layer on ladder or cleats (B.52.17 row 5)",
    "buried_touching": "Direct in ground, touching (B.52.18)",
    "buried_1d": "Direct in ground, one cable diameter apart (B.52.18)",
    "buried_0125m": "Direct in ground, 0.125 m apart (B.52.18)",
    "buried_025m": "Direct in ground, 0.25 m apart (B.52.18)",
    "buried_05m": "Direct in ground, 0.5 m apart (B.52.18)",
    "ducts_mc_touching": "Multi-core in ducts, touching (B.52.19 A)",
    "ducts_mc_025m": "Multi-core in ducts, 0.25 m apart (B.52.19 A)",
    "ducts_mc_05m": "Multi-core in ducts, 0.5 m apart (B.52.19 A)",
    "ducts_mc_1m": "Multi-core in ducts, 1.0 m apart (B.52.19 A)",
    "ducts_sc_touching": "Single-core in ducts, touching (B.52.19 B)",
    "ducts_sc_025m": "Single-core in ducts, 0.25 m apart (B.52.19 B)",
    "ducts_sc_05m": "Single-core in ducts, 0.5 m apart (B.52.19 B)",
    "ducts_sc_1m": "Single-core in ducts, 1.0 m apart (B.52.19 B)",
}


def _ampacity():
    """{key: {loaded: {method: {size: amps}}}} with numeric keys."""
    out = {}
    for key, by_loaded in DATA["ampacity"].items():
        for loaded, by_method in by_loaded.items():
            for method, cells in by_method.items():
                out.setdefault(key, {}).setdefault(int(loaded), {})[method] = {
                    float(s): float(v) for s, v in cells.items()}
    return out


def _grouping():
    g = {}
    for fam, env in (("grouping_air_b52_17", "air"), ("grouping_buried_b52_18", "buried"),
                     ("grouping_ducts_b52_19", "ducts")):
        for name, row in DATA[fam].items():
            g[name] = {"env": env, "factors": {int(n): float(v) for n, v in row.items()}}
    return g


def _num(v):
    return repr(int(v)) if float(v).is_integer() else repr(float(v))


def _py():
    amp, grp = _ampacity(), _grouping()
    L = ['"""GENERATED by testing/iec-60364-tables-review/build_iec_tables.py — do not edit.',
         "",
         "IEC 60364-5-52 current-carrying capacities and grouping factors.",
         f"Source: {DATA['_source']}",
         '"""', "",
         "# Table B.52.1 reference methods: code -> (description, environment, tables)",
         "IEC_METHODS = {"]
    for code, desc, env, tables in METHODS:
        L.append(f"    {code!r}: ({desc!r}, {env!r}, {tables!r}),")
    L += ["}", "",
          "# {'<ins>_<cond>': {loaded conductors: {method: {size_mm2: A}}}}",
          "# 2 loaded = single-phase (B.52.2/.3, B.52.10–.13 cols 2/4), 3 loaded = three-phase",
          "IEC_AMPACITY = {"]
    for key in sorted(amp):
        L.append(f"    {key!r}: {{")
        for loaded in sorted(amp[key]):
            L.append(f"        {loaded}: {{")
            for m in [c for c, *_ in METHODS if c in amp[key][loaded]]:
                cells = ", ".join(f"{_num(s)}: {_num(v)}" for s, v in sorted(amp[key][loaded][m].items()))
                L.append(f"            {m!r}: {{{cells}}},")
            L.append("        },")
        L.append("    },")
    L += ["}", "",
          "# Grouping reduction factors: name -> {'env': air|buried|ducts, 'factors': {circuits: f}}",
          "IEC_GROUPING = {"]
    for name in GROUP_LABELS:
        row = grp[name]
        cells = ", ".join(f"{n}: {_num(v)}" for n, v in sorted(row["factors"].items()))
        L.append(f"    {name!r}: {{'env': {row['env']!r}, 'factors': {{{cells}}}}},")
    L += ["}", "", "IEC_GROUPING_LABELS = {"]
    for name, label in GROUP_LABELS.items():
        L.append(f"    {name!r}: {label!r},")
    L += ["}", ""]
    return "\n".join(L)


def _js():
    amp, grp = _ampacity(), _grouping()
    L = ["/* GENERATED by testing/iec-60364-tables-review/build_iec_tables.py — do not edit.",
         " * IEC 60364-5-52 current-carrying capacities and grouping factors (twin of",
         " * backend/analysis/iec_60364_data.py).",
         f" * Source: {DATA['_source']} */", "",
         "// Table B.52.1 reference methods",
         "const IEC_INSTALLATION_METHODS = ["]
    for code, desc, env, tables in METHODS:
        L.append(f"  {{ code: {json.dumps(code)}, description: {json.dumps(desc)}, env: {json.dumps(env)}, tables: {json.dumps(tables)} }},")
    L += ["];", "",
          "// { '<ins>_<cond>': { loaded conductors: { method: { size_mm2: A } } } }",
          "const IEC_AMPACITY = {"]
    for key in sorted(amp):
        L.append(f"  {key}: {{")
        for loaded in sorted(amp[key]):
            L.append(f"    {loaded}: {{")
            for m in [c for c, *_ in METHODS if c in amp[key][loaded]]:
                cells = ", ".join(f"'{_num(s)}': {_num(v)}" for s, v in sorted(amp[key][loaded][m].items()))
                L.append(f"      {m}: {{ {cells} }},")
            L.append("    },")
        L.append("  },")
    L += ["};", "",
          "// Grouping reduction factors: name -> { env: air|buried|ducts, factors: { circuits: f } }",
          "const IEC_GROUPING = {"]
    for name in GROUP_LABELS:
        row = grp[name]
        cells = ", ".join(f"{n}: {_num(v)}" for n, v in sorted(row["factors"].items()))
        L.append(f"  {name}: {{ env: {json.dumps(row['env'])}, factors: {{ {cells} }} }},")
    L += ["};", "", "const IEC_GROUPING_LABELS = {"]
    for name, label in GROUP_LABELS.items():
        L.append(f"  {name}: {json.dumps(label)},")
    L += ["};", ""]
    return "\n".join(L)


if __name__ == "__main__":
    (ROOT / "backend/analysis/iec_60364_data.py").write_text(_py())
    (ROOT / "frontend/js/iec-60364-data.js").write_text(_js())
    print("wrote backend/analysis/iec_60364_data.py and frontend/js/iec-60364-data.js")
