/* ProtectionPro — Plan Markup annotated-plan export (PNG + PDF sheet).
 *
 * Rasterizes the marked-up plan (background image + all markup, honoring the
 * crop box) via PlanEngine.renderExport, then downloads a PNG or lays it into
 * an A3 jsPDF drawing sheet with a title-block strip (project, date, scale
 * note, active discipline layer's drawing no / revision).
 */

const PlanExport = {
  MAX_DIM: 6000,   // cap the longest raster side (memory + PDF weight)

  _worldRect() { return PlanEngine.exportWorldRect(0.03); },

  // Offscreen render → {canvas, w, h} at a scale fit to MAX_DIM.
  _render() {
    const wr = this._worldRect();
    if (!wr) { UI.toast('Nothing to export yet.', 'info'); return null; }
    const wWorld = Math.max(1, wr.maxX - wr.minX), hWorld = Math.max(1, wr.maxY - wr.minY);
    let scale = Math.min(this.MAX_DIM / wWorld, this.MAX_DIM / hWorld, 4);
    if (!isFinite(scale) || scale <= 0) scale = 1;
    const w = Math.max(1, Math.round(wWorld * scale)), h = Math.max(1, Math.round(hWorld * scale));
    const canvas = document.createElement('canvas');
    canvas.width = w; canvas.height = h;
    const ctx = canvas.getContext('2d');
    ctx.fillStyle = '#ffffff'; ctx.fillRect(0, 0, w, h);
    PlanEngine.renderExport(ctx, wr, scale);
    return { canvas, w, h };
  },

  _baseName() { return (AppState.projectName || 'plan').replace(/[^\w-]+/g, '_'); },

  exportPNG() {
    const r = this._render(); if (!r) return;
    r.canvas.toBlob((blob) => {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url; a.download = `${this._baseName()}_plan.png`;
      document.body.appendChild(a); a.click(); a.remove();
      setTimeout(() => URL.revokeObjectURL(url), 1000);
    }, 'image/png');
  },

  exportPDF() {
    const r = this._render(); if (!r) return;
    const jsPDFctor = window.jspdf && window.jspdf.jsPDF;
    if (!jsPDFctor) { UI.alert('PDF library not available.'); return; }
    const landscape = r.w >= r.h;
    const doc = new jsPDFctor({ orientation: landscape ? 'landscape' : 'portrait', unit: 'mm', format: 'a3' });
    const pageW = doc.internal.pageSize.getWidth();
    const pageH = doc.internal.pageSize.getHeight();
    const margin = 8;
    const titleW = 70;                       // right-hand title-block strip
    const drawW = pageW - margin * 2 - titleW;
    const drawH = pageH - margin * 2;

    // Fit the raster into the drawing area, preserving aspect.
    const ar = r.w / r.h;
    let iw = drawW, ih = drawW / ar;
    if (ih > drawH) { ih = drawH; iw = drawH * ar; }
    const img = r.canvas.toDataURL('image/jpeg', 0.9);
    doc.addImage(img, 'JPEG', margin, margin, iw, ih);
    // Drawing-area border
    doc.setDrawColor(60); doc.setLineWidth(0.3);
    doc.rect(margin, margin, drawW, drawH);

    // Title block
    const tbX = margin + drawW;
    doc.rect(tbX, margin, titleW, drawH);
    const layer = AppState.planMarkup.layers.find(l => l.id === AppState.planMarkup.activeLayerId);
    const scale = AppState.planMarkup.scale;
    const rows = [
      ['PROJECT', AppState.projectName || ''],
      ['DRAWING', layer ? layer.name : 'Plan Markup'],
      ['DRAWING No', (layer && layer.drawingNo) || ''],
      ['REVISION', (layer && layer.revision) || ''],
      ['SCALE', scale ? `1 px = ${scale.factor.toFixed(4)} m` : 'NTS'],
      ['DATE', (AppState.projectDetails && AppState.projectDetails.date) || ''],
      ['DRAWN', (AppState.projectDetails && AppState.projectDetails.engineerName) || ''],
      ['CLIENT', (AppState.projectDetails && AppState.projectDetails.client) || ''],
    ];
    let ty = margin;
    const rowH = 12;
    doc.setFontSize(7);
    for (const [k, v] of rows) {
      doc.rect(tbX, ty, titleW, rowH);
      doc.setTextColor(120); doc.text(k, tbX + 2, ty + 4);
      doc.setTextColor(20); doc.setFontSize(9);
      doc.text(String(v).slice(0, 32), tbX + 2, ty + 9);
      doc.setFontSize(7);
      ty += rowH;
    }
    doc.setFontSize(6); doc.setTextColor(140);
    doc.text('Generated by ProtectionPro — Plan Markup', tbX + 2, pageH - margin - 2);

    doc.save(`${this._baseName()}_plan.pdf`);
  },
};
